### ISSUE TITLE
Prijava na bazo, košarica, SQL injection

### ISSUE THREAD

**Issue by jaanos** [MartinDolenc/OPB-Ne_se_ena_spletna_trgovina#2]
@MartinDolenc, kot si sam opozoril, imaš trenutno v `auth_public.py` svoje geslo. Da bo lahko aplikacija delovala z uporabnikom `javnost`, bo potrebno nastaviti še pravice na tabelah (kolikor vidim, pravico povezovanja na bazo že ima), npr.
```sql
GRANT SELECT ON ALL TABLES IN SCHEMA public TO javnost; -- branje iz vseh tabel
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO javnost; -- uporaba vseh števcev
GRANT INSERT, UPDATE, DELETE ON uporabnik TO javnost; -- potrebne pravice na tabeli uporabnik
...
```
Ko to urediš, svoje geslo seveda zamenjaj, saj je trenutno za vekomaj objavljeno na internetu.

Kar se tiče košarice, svetujem, da jo shranjuješ v obliki JSON. Nekaj takega bi šlo:
```python
import json

def vsebina_kosare():
    """Funkcija za pridobivanje vsebine košarice kot množice."""
    kosara = request.get_cookie('kosara', secret=secret)
    if kosara is None:
        return set()
    try:
        return set(json.loads(kosara))
    except json.JSONDecodeError:
        return set()

@post('/dodaj_v_kosaro/<x:int>/') # x je lahko samo celo število!
def dodaj_v_kosaro(x):
    kosara = vsebina_kosare()
    kosara.symmetric_difference_update({x}) # doda v košaro, če ga še ni, sicer ga odstrani
    response.set_cookie('kosara', json.dumps(list(kosara)), path='/', secret=secret)
```
Potem lahko kličeš `vsebina_kosare()`, kadarkoli jo potrebuješ (tako ti bo tudi preverjanje vsebovanosti delovalo pravilno - pri trenutni implementaciji namreč gledaš podnize, kar vsekakor ni ustrezno). Tako se lahko znebiš nevarnih poizvedb - namesto
https://github.com/MartinDolenc/OPB-Ne_se_ena_spletna_trgovina/blob/4611d81d43fc969b48b5f211773e540ed665162e/main.py#L289
lahko potem narediš
```python
cur.execute("SELECT * FROM izdelek WHERE id IN ({})".format(", ".join("%s" for _ in kosara)), tuple(kosara)) 
```

Opazil sem še, da pri izdelku dobim gumb *Odstrani iz zaželjenih*, če ga ima katerikoli uporabnik med zaželenimi. Prav tako iskanje deluje samo iz začetne strani (pri `<form>` bo potrebno dodati atribut `action`).

Glede na to, da aplikacija sicer deluje, bom dodal povezavo na repozitorij predmeta. Če se še nisi, se lahko torej z @alenFMF domeniš za termin zagovora. Če boš še kaj spreminjal, mi javi, da posodobim povezavo.

**Comment by MartinDolenc** [comment]
Sem implementiral vaše predloge. #3 #4 #5

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo. Opažam še, da pride do napake na strani izdelka, če uporabnik ni prijavljen.
